services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: nom
      POSTGRES_PASSWORD: nom
      POSTGRES_DB: nom
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

